[package]
name = "secrets_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfg-if = "1.0"
thiserror = "1.0.38"

[target.'cfg(target_os = "windows")'.dependencies.windows-sys]
features = [
  "Win32_Foundation",
  "Win32_Security_Credentials",
  "Win32_System_Diagnostics_Debug",
  "Win32_System_Memory",
  "Win32_System_WindowsProgramming",
]
version = "0.48.0"

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.9.3"
core-foundation-sys = "0.8.4"

[target.'cfg(any(target_os = "freebsd", target_os = "linux"))'.dependencies]
glib = "0.18.2"
glib-sys = "0.18.1"
gio = "0.18.2"
libsecret = "0.4.0"
libsecret-sys = "0.4.0"