[package]
edition = "2021"
name = "keyring"
version = "1.0.0"
authors = ["Zowe Project"]
license = "EPL-2.0"
repository = "https://github.com/zowe/zowe-cli"

[lib]
crate-type = ["cdylib"]

[dependencies]
cfg-if = "1.0"
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = {version = "2", default-features = false, features = ["napi4"]}
napi-derive = "2"
thiserror = "1.0.38"

[target.'cfg(target_os = "windows")'.dependencies.windows-sys]
features = [
  "Win32_Foundation",
  "Win32_Security_Credentials",
  "Win32_System_Diagnostics_Debug",
  "Win32_System_Memory",
  "Win32_System_WindowsProgramming",
]
version = "0.48.0"

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.9.3"
cvt = "0.1.2"

[target.'cfg(any(target_os = "freebsd", target_os = "linux"))'.dependencies]
glib = "0.17.10"
gio = "0.17.10"
libsecret = "0.3.0"
libsecret-sys = "0.3.0"

[build-dependencies]
napi-build = "2"

[profile.release]
lto = true
opt-level = "z"  # Optimize for size.
strip = "symbols"